version: "3"

services:
  chrome:
    image: selenium/standalone-chrome:debug
    ports:
      - 4444:4444
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
